/**
 * KKL Dctm Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentUpdateInfoAllOf { 
    /**
     * The extension of the file
     */
    fileExtension?: string;
    /**
     * The body of the file
     */
    fileBody?: string;
    /**
     * The check in policy
     */
    versionPolicy?: DocumentUpdateInfoAllOf.VersionPolicyEnum;
}
export namespace DocumentUpdateInfoAllOf {
    export type VersionPolicyEnum = 'MAJOR_VERSION' | 'MINOR_VERSION' | 'SAME_VERSION';
    export const VersionPolicyEnum = {
        MajorVersion: 'MAJOR_VERSION' as VersionPolicyEnum,
        MinorVersion: 'MINOR_VERSION' as VersionPolicyEnum,
        SameVersion: 'SAME_VERSION' as VersionPolicyEnum
    };
}


