/**
 * KKL Dctm Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Attribute } from './attribute';


export interface DocumentUpdateInfo { 
    /**
     * The id of the application
     */
    appId: string;
    /**
     * The id of the document in Documentum
     */
    objectId: string;
    /**
     * The attributes of the folder.
     */
    attributes?: Array<Attribute>;
    /**
     * The extension of the file
     */
    fileExtension?: string;
    /**
     * The body of the file
     */
    fileBody?: string;
    /**
     * The check in policy
     */
    versionPolicy?: DocumentUpdateInfo.VersionPolicyEnum;
}
export namespace DocumentUpdateInfo {
    export type VersionPolicyEnum = 'MAJOR_VERSION' | 'MINOR_VERSION' | 'SAME_VERSION';
    export const VersionPolicyEnum = {
        MajorVersion: 'MAJOR_VERSION' as VersionPolicyEnum,
        MinorVersion: 'MINOR_VERSION' as VersionPolicyEnum,
        SameVersion: 'SAME_VERSION' as VersionPolicyEnum
    };
}


