/**
 * KKL Dctm Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FolderContentInfoAllOf { 
    /**
     * The index of the requested page starts from 0
     */
    pageNumber?: number;
    /**
     * Number of items in the page
     */
    pageSize?: number;
    /**
     * Query filter ALL folders and documents
     */
    filter?: FolderContentInfoAllOf.FilterEnum;
}
export namespace FolderContentInfoAllOf {
    export type FilterEnum = 'ALL' | 'FOLDERS' | 'DOCUMENTS';
    export const FilterEnum = {
        All: 'ALL' as FilterEnum,
        Folders: 'FOLDERS' as FilterEnum,
        Documents: 'DOCUMENTS' as FilterEnum
    };
}


