/**
 * KKL Dctm Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Attribute } from './attribute';


export interface FolderInInfo { 
    /**
     * The id of the application
     */
    appId: string;
    /**
     * The name of the folder.
     */
    objectName: string;
    /**
     * The folder type.
     */
    objectType?: string;
    /**
     * The attributes of the folder.
     */
    attributes?: Array<Attribute>;
    /**
     * The path to save the folder in documentum.
     */
    repositoryPath?: string;
}

