/**
 * KKL Dctm Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Attribute } from './attribute';


export interface SearchContentInfo { 
    /**
     * The id of the application
     */
    appId: string;
    /**
     * The search term
     */
    searchTerm: string;
    /**
     * The search path
     */
    searchPath?: string;
    /**
     * The attributes for the search.
     */
    attributes?: Array<Attribute>;
    /**
     * The fulltext query id saved in documentum side dqlquery.xml
     */
    queryId?: string;
}

